I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 557, in script
    $ tetras[2] += 2
  File "game/script.rpy", line 557, in <module>
    $ tetras[2] += 2
NameError: name 'tetras' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 557, in script
    $ tetras[2] += 2
  File "C:\Users\Black Cat\Downloads\renpy-7.4.11-sdk/renpy/ast.py", line 928, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\Black Cat\Downloads\renpy-7.4.11-sdk/renpy/python.py", line 2245, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 557, in <module>
    $ tetras[2] += 2
NameError: name 'tetras' is not defined

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
Dustborn 1.0
Tue Mar 22 17:28:28 2022
